/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD_ADMIN;
import Login.LOGIN_ADMIN;
import javax.swing.JOptionPane;
import ORM.Penayangan;

public final class EditPenayangan extends javax.swing.JFrame {
    private String idPenayanganToEdit;
    private Penayangan penayangan;

    public EditPenayangan() {
        initComponents();
        penayangan = new Penayangan();
    }
    
    private void showPenayanganData() {
        penayangan.idPenayangan = idPenayanganToEdit;
        penayangan = Penayangan.getPenayanganById(penayangan.idPenayangan);

        if (penayangan != null) {
            // Display Penayangan data in the form
            Id_Penayangan.setText(penayangan.idPenayangan);
            Tanggal_Penayangan.setDate(penayangan.tanggal);
            Waktu_Penayangan.setText(penayangan.waktu);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Id_Penayangan = new javax.swing.JTextField();
        Waktu_Penayangan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        Edit_Penayangan = new javax.swing.JButton();
        Tanggal_Penayangan = new com.toedter.calendar.JDateChooser();
        Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 308));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CGY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 30, 123, 70);

        Id_Penayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_PenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(Id_Penayangan);
        Id_Penayangan.setBounds(300, 120, 164, 30);

        Waktu_Penayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Waktu_PenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(Waktu_Penayangan);
        Waktu_Penayangan.setBounds(300, 160, 164, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Id Penayangan :");
        jLabel1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jLabel1ComponentAdded(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 130, 100, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Waktu :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 170, 44, 16);

        Waktu.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        Waktu.setText("Tanggal :");
        jPanel1.add(Waktu);
        Waktu.setBounds(240, 210, 70, 20);

        Edit_Penayangan.setText("Edit");
        Edit_Penayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit_PenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(Edit_Penayangan);
        Edit_Penayangan.setBounds(390, 250, 72, 23);
        jPanel1.add(Tanggal_Penayangan);
        Tanggal_Penayangan.setBounds(300, 202, 164, 30);

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Kembali);
        Kembali.setBounds(10, 10, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/FOTO GUI/CRUD.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -10, 630, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jLabel1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1ComponentAdded

    private void Id_PenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_PenayanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_PenayanganActionPerformed

    private void Waktu_PenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Waktu_PenayanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Waktu_PenayanganActionPerformed

    private void Edit_PenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit_PenayanganActionPerformed

        penayangan.idPenayangan = Id_Penayangan.getText();
        java.util.Date tanggalDate = Tanggal_Penayangan.getDate();
        penayangan.waktu = Waktu_Penayangan.getText();
        penayangan.adminId = LOGIN_ADMIN.idLoginAdmin;

        if (penayangan.idPenayangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Id Penayangan harus diisi.");
        } else if (tanggalDate != null) {

            penayangan.tanggal = new java.sql.Date(tanggalDate.getTime());


            if (penayangan.updatePenayangan()) {
                JOptionPane.showMessageDialog(this, "Data penayangan berhasil diubah.");

            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengubah data penayangan.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tanggal harus diisi.");
        }

    }//GEN-LAST:event_Edit_PenayanganActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        this.setVisible(false);
        new MENU_ADMIN().setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditPenayangan frame = new EditPenayangan();
                frame.setLocationRelativeTo(null); // Menempatkan frame di tengah layar
                frame.setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Edit_Penayangan;
    private javax.swing.JTextField Id_Penayangan;
    private javax.swing.JButton Kembali;
    private com.toedter.calendar.JDateChooser Tanggal_Penayangan;
    private javax.swing.JLabel Waktu;
    private javax.swing.JTextField Waktu_Penayangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
