/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD_ADMIN;
import javax.swing.JOptionPane;
import ORM.Penayangan;

public final class HapusPenayangan extends javax.swing.JFrame {

    public HapusPenayangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IdPenayangan = new javax.swing.JTextField();
        IdFilm = new javax.swing.JTextField();
        HapusFilm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 308));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CGY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 40, 123, 60);

        IdPenayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(IdPenayangan);
        IdPenayangan.setBounds(250, 142, 191, 30);

        IdFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFilmActionPerformed(evt);
            }
        });
        jPanel1.add(IdFilm);
        IdFilm.setBounds(250, 192, 191, 30);

        HapusFilm.setText("Hapus");
        HapusFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusFilmActionPerformed(evt);
            }
        });
        jPanel1.add(HapusFilm);
        HapusFilm.setBounds(370, 240, 72, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Id Film :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(190, 200, 50, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText("Id Penayangan :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 150, 100, 20);

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Kembali);
        Kembali.setBounds(10, 20, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/FOTO GUI/CRUD.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, -10, 640, 330);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFilmActionPerformed

    private void HapusFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusFilmActionPerformed
         String Id_Penayangan = IdPenayangan.getText();
         String Id_Film = IdFilm.getText();

         Penayangan penayangan = new Penayangan(Id_Penayangan, null, null, null, Id_Film, null);

         if (penayangan.deletePenayangan()) {
             JOptionPane.showMessageDialog(this, "Data penayangan berhasil dihapus.");
             resetInputFields();
         } else {
             JOptionPane.showMessageDialog(this, "Gagal menghapus data penayangan.");
         } 
   
    }//GEN-LAST:event_HapusFilmActionPerformed

    private void IdPenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPenayanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPenayanganActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        this.setVisible(false);
        new MENU_ADMIN().setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HapusPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HapusPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HapusPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HapusPenayangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HapusPenayangan().setVisible(true);
            }
        });
    }
    private void resetInputFields() {
    IdPenayangan.setText("");
    IdFilm.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusFilm;
    private javax.swing.JTextField IdFilm;
    private javax.swing.JTextField IdPenayangan;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
