/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD_ADMIN;

public final class MENU_ADMIN extends javax.swing.JFrame {

    public MENU_ADMIN() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TambahPenayangan = new javax.swing.JButton();
        UbahPenayangan = new javax.swing.JButton();
        HapusPenayangan = new javax.swing.JButton();
        LihatPenayangan = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 308));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 45)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CGY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 50, 107, 60);

        TambahPenayangan.setText("Tambah Penayangan");
        TambahPenayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahPenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(TambahPenayangan);
        TambahPenayangan.setBounds(150, 130, 160, 50);

        UbahPenayangan.setText("Ubah Penayangan");
        UbahPenayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahPenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(UbahPenayangan);
        UbahPenayangan.setBounds(150, 190, 160, 50);

        HapusPenayangan.setText("Hapus Penayangan");
        HapusPenayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusPenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(HapusPenayangan);
        HapusPenayangan.setBounds(350, 130, 150, 50);

        LihatPenayangan.setText("Lihat Penayangan");
        LihatPenayangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatPenayanganActionPerformed(evt);
            }
        });
        jPanel1.add(LihatPenayangan);
        LihatPenayangan.setBounds(350, 190, 150, 50);

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar);
        Keluar.setBounds(20, 20, 80, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/FOTO GUI/menu.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 630, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahPenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahPenayanganActionPerformed
        this.setVisible(false);
        new TambahPenayangan().setVisible(true);
    }//GEN-LAST:event_TambahPenayanganActionPerformed

    private void HapusPenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusPenayanganActionPerformed
        this.setVisible(false);
        new HapusPenayangan().setVisible(true);
    }//GEN-LAST:event_HapusPenayanganActionPerformed

    private void UbahPenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahPenayanganActionPerformed
        this.setVisible(false);
        new EditPenayangan().setVisible(true);
    }//GEN-LAST:event_UbahPenayanganActionPerformed

    private void LihatPenayanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatPenayanganActionPerformed
        this.setVisible(false);
        new LihatPenayangan().setVisible(true);
    }//GEN-LAST:event_LihatPenayanganActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        this.dispose();
        System.exit(0);        
    }//GEN-LAST:event_KeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU_ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MENU_ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusPenayangan;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton LihatPenayangan;
    private javax.swing.JButton TambahPenayangan;
    private javax.swing.JButton UbahPenayangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
