/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRUD_SUPERADMIN;

import javax.swing.JOptionPane;
import ORM.Film;

public final class EditFilm extends javax.swing.JFrame {

    /**
     * Creates new form EditFilm
     */
    public EditFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        IdFilm = new javax.swing.JTextField();
        Judul_FilmBaru = new javax.swing.JTextField();
        EditFilm = new javax.swing.JButton();
        Genre_FilmBaru = new javax.swing.JTextField();
        Durasi_FilmBaru = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(632, 302));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 44)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CGY");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(270, 30, 123, 70);

        IdFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdFilmActionPerformed(evt);
            }
        });
        jPanel1.add(IdFilm);
        IdFilm.setBounds(280, 122, 191, 30);

        Judul_FilmBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Judul_FilmBaruActionPerformed(evt);
            }
        });
        jPanel1.add(Judul_FilmBaru);
        Judul_FilmBaru.setBounds(280, 162, 191, 30);

        EditFilm.setText("Edit");
        EditFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditFilmActionPerformed(evt);
            }
        });
        jPanel1.add(EditFilm);
        EditFilm.setBounds(480, 250, 60, 23);

        Genre_FilmBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Genre_FilmBaruActionPerformed(evt);
            }
        });
        jPanel1.add(Genre_FilmBaru);
        Genre_FilmBaru.setBounds(280, 202, 191, 30);

        Durasi_FilmBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Durasi_FilmBaruActionPerformed(evt);
            }
        });
        jPanel1.add(Durasi_FilmBaru);
        Durasi_FilmBaru.setBounds(280, 242, 191, 30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText(" Id Film :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(220, 130, 50, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel2.setText(" Judul Film Baru :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 170, 100, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Genre Film Baru :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(170, 210, 100, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel6.setText("Durasi Film Baru :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 250, 110, 20);

        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });
        jPanel1.add(Kembali);
        Kembali.setBounds(10, 10, 80, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FOTO/FOTO GUI/CRUD.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 630, 300);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditFilmActionPerformed
        String Id_Film = IdFilm.getText();
        String Judul = Judul_FilmBaru.getText();
        String Durasi = Durasi_FilmBaru.getText();
        String Genre = Genre_FilmBaru.getText();


        Film film = new Film(Id_Film, Judul, Durasi, Genre, null);

        // Panggil metode update dari objek Film
        boolean updated = film.update();

        if (updated) {
            JOptionPane.showMessageDialog(this, "Data film berhasil diperbarui.");
            resetInputFields();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data film.");
        }
    
    }//GEN-LAST:event_EditFilmActionPerformed

    private void IdFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdFilmActionPerformed

    private void Judul_FilmBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Judul_FilmBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Judul_FilmBaruActionPerformed

    private void Genre_FilmBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Genre_FilmBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Genre_FilmBaruActionPerformed

    private void Durasi_FilmBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Durasi_FilmBaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Durasi_FilmBaruActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        this.setVisible(false);
        new MENU_SUPERADMIN(null).setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Durasi_FilmBaru;
    private javax.swing.JButton EditFilm;
    private javax.swing.JTextField Genre_FilmBaru;
    private javax.swing.JTextField IdFilm;
    private javax.swing.JTextField Judul_FilmBaru;
    private javax.swing.JButton Kembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

// Metode untuk mereset input fields
    private void resetInputFields() {
        IdFilm.setText("");
        Judul_FilmBaru.setText("");
        Genre_FilmBaru.setText("");
        Durasi_FilmBaru.setText("");
    }


}
